version: '3.1'

services:
  db:
    image: mysql
    container_name: order-management-database
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: OrderManagement
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - om-db:/var/lib/mysql
volumes:
  om-db: